### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by maxrimue**
First of all: Thanks for creating this project.
I've been using it in one of my repos, however, when using [david-dm](https://david-dm.org/) it showed me that my dependencies are "Insecure". I think this is related to hpp, because it uses outdated modules. This change should just update the dependencies, everything should work as expected, since those are just minor updates, so updates not changing or removing any existing API.

### CODE REVIEW

**Comment by maxrimue** [comment]
Seems like it's failing for 0.10.0, could this be because of the devDependencies?

**Comment by maxrimue** [comment]
There we go. It seems like something was wrong with the coveralls plugin

**Comment by analog-nico** [comment]
Hi @maxrimue thanks for working on this!

Thanks to your PR I checked http://semver.org for the first time and OMG I always had a wrong understanding of semantic versioning!

To make sure people don't risk to install a too old dependency would you mind changing all versions - e.g. for lodash - from `3.x.x` to `^3.8`?

I can afterwards configure TravisCI to build with lodash 3.8.0 + type-is 1.6.0 and also with lodash latest + type-is latest.

**Comment by maxrimue** [comment]
@analog-nico Do you explicitly want lodash in version 3.8 or higher, or can it be also 3.9 or higher?

**Comment by analog-nico** [comment]
Good point. Take the highest version available today.

**Comment by maxrimue** [comment]
Done

**Comment by analog-nico** [comment]
Hi @maxrimue I just published version 0.2.0 with it's dependencies up-to-date. Cheers!

**Comment by maxrimue** [comment]
@analog-nico Glad to hear that, thanks :+1:

**Pull request merged**
